---
dotfiles_dir: '{{ ansible_env.HOME }}/.dotfiles'
pre_tasks_dir: '{{ dotfiles_dir }}/pre_tasks'
templates_dir: '{{ dotfiles_dir }}/templates'

# Default roles to run if no roles are specified
default_roles:
  # Standalone roles
  - system
  - fonts
  - lua
  - fzf
  - nvm

  # Dependant roles
  - zsh
  - neovim
