---
- name: Heroku CLI | Install via script
  become: true
  ansible.builtin.shell: "curl -sSL https://cli-assets.heroku.com/install.sh | sh"
  args:
    creates: /usr/local/bin/heroku
  changed_when: true
