---
- name: Install VM packages
  become: true
  ansible.builtin.package:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-manager
    state: present
    update_cache: true

- name: Add user to libvirt and kvm groups
  become: true
  ansible.builtin.user:
    name: '{{ remote.USER }}'
    groups: libvirt,kvm
    append: true
