---
kitty_install_dir: '{{ remote.HOME }}/.local/kitty.app'
kitty_bin_dir: '{{ remote.HOME }}/.local/bin'
kitty_desktop_dir: '{{ remote.HOME }}/.local/share/applications'
kitty_config_dir: '{{ remote.HOME }}/.config/kitty'
kitty_installer: '{{ remote.HOME }}/kitty_installer.sh'
