---

standalone_roles:
  - system
  - fonts
  - lua
  - fzf
  - nvm
  - node
  - npm
  - ssh
  - tmux
  - docker
  - kitty
  - glab
  - scripts
  - browser
  - swift
  - zoxide
  - scripts

wayland_roles:
  - chaotic_aur
  - hyprland
  - waybar
  - wofi
  - gtk_theme
  - dunst
  - wallpaper
  - filemanager
  - desktop_essentials

xorg_roles:
  - i3
  - picom
  - rofi
  - polybar

dependent_roles:
  - zsh
  - neovim
  - browser

future_roles:
  # - vm
  # - github_cli
  # - heroku_cli
  # - uv
  # - openvpn
  # - android_studio
  # - intellij
  # - netbeans
  # - glassfish
  # - gemini_cli

default_roles: '{{ standalone_roles + wayland_roles + dependent_roles + xorg_roles }}'
# default_roles: '{{ standalone_roles + wayland_roles + dependent_roles + xorg_roles + future_roles }}'
