---

standalone_roles:
  - system
  - fonts
  - lua
  - fzf
  - nvm
  - node
  - npm
  - ssh
  - tmux
  - docker
  - kitty
  - glab

wayland_roles:
  - chaotic_aur
  - hyprland
  - waybar
  - wofi
  - gtk_theme
  - dunst
  - wallpaper
  - filemanager
  - desktop_essentials

xorg_roles:
  - i3
  - picom
  - rofi
  - polybar

dependent_roles:
  - zsh
  - neovim
default_roles: '{{ standalone_roles + wayland_roles + dependent_roles }}'
