---
# Default roles to run if no roles are specified
default_roles:
  # Standalone roles
  - system
  - fonts
  - lua
  - fzf
  - nvm
  - node
  - npm
  - ssh
  - tmux
  - docker
  - kitty
  - glab
  - picom
  - rofi
  - polybar
  - hyprland

  # Dependant roles
  - zsh
  - neovim
  - i3
