---
ssh_keys:
  - name: personal_github_ed25519
    config:
      host: github.com
      hostname: github.com
      user: git
      identity_file: ~/.ssh/personal_github_ed25519
    private_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      30633633303536363561396434306465626436363665656435393133376163383964393636333761
      3966336461616665623039373534303164326166643936320a653264333936386465363433363735
      65393234643639363134613065393065656361653231356535643965313833623531353163666663
      3336333930666636360a336430646337336536333236343137656537643237613464396533633361
      38343161383235303361393163353336393432633236353764363537626339316363663865393365
      38653734653539393963343062383364353535396366643361326431303735643564616662373134
      65663235323236346539306239663464353261376331313964326563393335613730616433303230
      38306339666439303635383765393861393761396134333438303333643364346230333265623339
      63653465333536316366646165366231623563643163656231663139373330316635316534316665
      66343332373131323562396565346362353763333262326664316362613937303735613834326437
      33623834303632393662386135386530623139373036343330303434666362346331616662313164
      30383232383333613438333737613766396532323132616333343736616635646161373039373532
      36626330323636393464313233663130313037373532616231313433313831626662353539643661
      32356536643434323230346538303966613466333462393462636536643331396438313733393064
      38333836333534343462353266306661343964366430633130626163363366613566373233303166
      65643334393264666234336563393238666436343930633631653438373839393265373635313730
      39366263393465396461643837396666346633373139363732386339626336386166333736323464
      31663238386534313266663633323331373835353865386665333063323332356366313663616365
      38313438306430613736653538343735346130393466336264323563653330333064353866356535
      39363138303862643461386635393439336432653763613666643039666637343039373962663366
      36326266356139353931363931383836316332303330393734396165333137363637323930666664
      66613331333464373861363637653632393465343038653766366139373433353730373630373239
      33613539636365323266356632376438643139613832653731653166653562323734653436373761
      33353635623737383065376633633962346664373136643238313264316162383031646330363230
      33383930393462333239663639626439613764323933623766626463663533353730
    public_key: !vault |-
      $ANSIBLE_VAULT;1.1;AES256
      34363834313936663030366539656633343866313063643932333161633664363161363564626239
      3064653261373033376435333333666537363364353233320a313863373737393233633266383334
      66643531386232356465636136623937626334316636313539383163643966343233333739373935
      6430336262666136320a333333386237616133376330303532616230366461393238343036633532
      34326337336534343933363864663933363936636636313566346661626637626336616234356435
      62353434656566383731363239643534373338666564653835623361333666356533613834316233
      61396530653834303232303161373530316631323065653135343836613234373435353033316662
      32303032346235333637613537613165643862343134306532336264366266386439636337363964
      31656334366432383366313430343030376133616130363166323530613430613334
