---
ssh_keys:
  - name: personal_github_ed25519
    config:
      host: github.com
      hostname: github.com
      user: git
      identity_file: ~/.ssh/personal_github_ed25519
    private_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      63316632633931346433656561363263643066303462656637353837383664653464666138386637
      3165643533613161383266373664343934303162653133610a393935356333623963303030393465
      65646530373662663938386465323734633338366334376636623566626161376265343132633962
      3339666532633339340a643037616630643835326235346137323862366435326663336138623462
      33636338306435313366616535613765643965653433343832636235363362363033323232313830
      34376235353330363265333938666631633831356464326130343935326661613639393635343034
      34396266663939633232623331663638643566373931653365333131323038653735666430653162
      38353361653032373838326237393162366566326661356134356263333235613937366332333762
      35336135323938303564366639396331336639643438613533393632333932663036373834313762
      34383062373531353630306332616363303637636633383764353733313062393835393833666566
      32663439313361346238656336333236326439383865326137646539636231353435613435323330
      32623162313036373731363963336637316430343831646363376564666566623064646535623132
      35333934303131626562346161336163613065356137313262613937386438303539333834343934
      65323736613037366630333031326530373731656264393563656330336535633733623764623966
      30613436626365623364303363643862336339383230663765633963636335333730623333393961
      65356461353937666338666138383633313836643634666438653664623865663034313866613862
      30356135303433653065396539356338343963373635633635613730616561383331666330633433
      62303236393334393130373430383138313135623038306434313862653036633966313636656431
      39663533616134613066326130616238666532623861636566326232663832633439633663346630
      33373263393661306561326335663263306465303530373936346337643463353638626137366661
      31336232643864646235383166396334333437383761646136643737353433616230656234643638
      35656632623031643162313138363537356532656466623837353966376561346231303930373539
      33636237356631323234613634306461666537623130373134373963303231613939373930653566
      38303137323335663332363062393766303632663937653839353039366538376235613265663330
      62653937396366393666623734373833636162393130313039626663393138383261303536363363
      62623939386531323463616633643333316431343566323634343465346236636664393937396430
      633366313233633833623239366136306564
    public_key: !vault |-
      $ANSIBLE_VAULT;1.1;AES256
      31616130323939626530613964636335396136663938316237306262363664376661333639333434
      6136386431333538396133653664343234643135653261330a306162666631333734336638636262
      34633462303439346436353433383038616633396534323764353663356438656331333166306362
      6630633764323935610a333666623339363262396464643863303364303132336430373239323033
      32616439376561613636326536643537616564306234383466643264623938323932323338316162
      37623835343033376233633234343163336637393566323866343163653131646536376162386466
      35333137613461636165323162643266303366666138303361396237613363636266616636346635
      33663361303032656130633462343363346461613730356362383336356130323535363531343030
      64643033616166356166633332613133343264613532393636613638613233376461
