---
android_studio_role_path: '{{ remote.dir.dotfiles }}/roles/android_studio'
# Placeholder URL for the latest Android Studio release.
# User should update this to the desired version.
android_studio_download_url: "https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.2.1.23/android-studio-2023.2.1.23-linux.tar.gz"
android_studio_install_dir: /opt/android-studio
android_studio_version: "2023.2.1.23" # e.g., '2023.2.1.23'
