---

- name: '{{ role_name }} | Update and Upgrade Packages'
  ansible.builtin.package:
    update_cache: true
    upgrade: true
  become: true

- name: '{{ role_name }} | Install Packages'
  ansible.builtin.package:
    name:
      - wget
      - python-pip
      - base-devel
      - cmake
      - jq
      - zip
      - unzip
    state: present
  become: true

- name: '{{ role_name }} | Install Dependencies'
  ansible.builtin.include_tasks: '{{ remote.distribution }}/install_libtexprintf.yml'
