---

- name: Update and Upgrade Packages
  ansible.builtin.package:
    update_cache: true
    upgrade: full
    autoremove: true
    autoclean: true
  become: true

- name: Install System Packages
  ansible.builtin.package:
    name:
      - wget
      - python3-pip
      - python3-venv
      - python3-dev
      - build-essential
      - cmake
      - jq
    state: present
    update_cache: true
  become: true

- name: Include libtexprintf build task
  ansible.builtin.include_tasks: '{{ distribution }}/install_libtexprint.yml'
