---

- name: Light | Install package
  become: true
  ansible.builtin.package:
    name: light
    state: present

- name: Light | Add user to video group
  become: true
  ansible.builtin.user:
    name: '{{ remote.USER }}'
    groups: video
    append: true

- name: Light | Set SUID permission
  become: true
  ansible.builtin.file:
    path: /usr/bin/light
    mode: 'u+s'
