---

- name: '{{ role_name }} | Checking for Distribution Config: {{ remote.distribution }}'
  ansible.builtin.stat:
    path: '{{ role_path }}/tasks/{{ remote.distribution }}.yml'
  register: distribution_config

- name: '{{ role_name }} | Run Tasks: {{ remote.distribution }}'
  ansible.builtin.include_tasks: '{{ remote.distribution }}.yml'
  when: distribution_config.stat.exists
