---

- name: Install Waybar Status Bar
  ansible.builtin.package:
    name: waybar
    state: present
  become: true

- name: Remove Waybar Config if exists
  ansible.builtin.file:
    path: '{{ waybar_config_dir }}'
    state: absent
  when: waybar_config_dir is not link

- name: Deploy Waybar Config
  ansible.builtin.file:
    src: '{{ waybar_config_src }}'
    dest: '{{ waybar_config_dir }}'
    state: link
    force: true
