---
github_cli_role_path: '{{ remote.dir.dotfiles }}/roles/github_cli'
github_cli_keyring: /etc/apt/keyrings/githubcli-archive-keyring.gpg
github_cli_repo_file: /etc/apt/sources.list.d/github-cli.list
