---

- name: FZF | Install FZF
  ansible.builtin.command: '{{ user_dir }}/.fzf/install --all --no-update-rc --no-fish'
  args:
    chdir: '{{ user_dir }}/.fzf'
  changed_when: false
  tags: fzf
  listen: install fzf
