---

- name: FZF | Install FZF
  ansible.builtin.command: '{{ remote.HOME }}/.fzf/install --all --no-update-rc
    --no-fish'
  args:
    chdir: '{{ remote.HOME }}/.fzf'
  changed_when: false
  tags: fzf
  listen: install fzf
