---

- name: Docker | Check if installed
  ansible.builtin.command: docker --version
  register: docker_check
  ignore_errors: true
  changed_when: false

- name: Docker | Remove old/conflicting Docker repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu
      {{ distribution_release }} stable
    state: absent
  become: true
  when: docker_check.failed  or docker_repo_file is file

- name: Docker | Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: Docker | Ensure keyring directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Docker | Add official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: '{{ docker_keyring }}'
    state: present

- name: Docker | Get system architecture
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_architecture
  changed_when: false

- name: Docker | Add stable repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ dpkg_architecture.stdout }} signed-by={{ docker_keyring }}]
      https://download.docker.com/linux/ubuntu {{ distribution_release }} stable
    state: present
    mode: '0644'

- name: Docker | Update APT cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Docker | Install Docker Engine
  become: true
  ansible.builtin.apt:
    name: '{{ docker_packages }}'
    state: present
    update_cache: true

- name: Docker | Enable and start service
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  when: not remote.is_wsl

- name: Docker | Add user to docker group
  become: true
  ansible.builtin.user:
    name: '{{ remote.USER }}'
    groups: docker
    append: true

- name: Docker | Copy daemon.json
  become: true
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: restart_docker
