---
- hosts: localhost
  connection: local
  pre_tasks:

    - name: Detect Host User
      ansible.builtin.include_tasks: '{{ pre_tasks_dir }}/whoami.yml'
      tags:
        - always

    - name: Gather installed packages
      ansible.builtin.include_tasks: '{{ pre_tasks_dir }}/gather_installed_packages.yml'
      tags:
        - always

  roles:
    - zsh
    - fonts
    - lua
