---
- hosts: arch_vm
  pre_tasks:

    - name: Gather installed packages
      ansible.builtin.include_tasks: '{{ local.dir.pre_tasks }}/gather_installed_packages.yml'
      tags:
        - always

    - name: Alias ansible facts
      ansible.builtin.include_tasks: '{{ local.dir.pre_tasks }}/alias_ansible_facts.yml'
      tags:
        - always

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ lookup('template', local.dir.templates ~ '/run_roles.j2') | from_yaml }}"
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - '{{ roles_item }}'
        name: '{{ roles_item }}'
      loop_control:
        loop_var: roles_item
      with_items: '{{ run_roles }}'
      tags:
        - always
