---

- name: Ensure fonts directory exists
  file:
    path: '{{ ansible_env.HOME }}/.local/share/fonts'
    state: directory
    mode: '0755'

- name: Download Nerd Font zip
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ nerd_font }}.zip
    dest: /tmp/{{ nerd_font }}.zip
    mode: '0644'

- name: Unzip Nerd Font
  unarchive:
    src: /tmp/{{ nerd_font }}.zip
    dest: '{{ ansible_env.HOME }}/.local/share/fonts'
    remote_src: true

- name: Refresh font cache
  command: fc-cache -fv
  changed_when: false
